/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author Temis juninho
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoRegistrar = new javax.swing.JButton();
        CaixaRegistrarUsuario = new javax.swing.JTextField();
        CaixaRegistrarSenha = new javax.swing.JTextField();
        CaixaRegistrarEmail = new javax.swing.JTextField();
        UsuarioTextRegistro = new javax.swing.JLabel();
        SenhaTextRegistro = new javax.swing.JLabel();
        EmailTextRegistro = new javax.swing.JLabel();
        RegistroText = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoRegistrar.setText("Registrar");
        BotaoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 90, 30));

        CaixaRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaRegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 170, 30));

        CaixaRegistrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaRegistrarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaRegistrarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 170, 30));

        CaixaRegistrarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaRegistrarEmailActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaRegistrarEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 170, 30));

        UsuarioTextRegistro.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        UsuarioTextRegistro.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioTextRegistro.setText("Usuario");
        getContentPane().add(UsuarioTextRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        SenhaTextRegistro.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        SenhaTextRegistro.setForeground(new java.awt.Color(255, 255, 255));
        SenhaTextRegistro.setText("Senha");
        getContentPane().add(SenhaTextRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        EmailTextRegistro.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        EmailTextRegistro.setForeground(new java.awt.Color(255, 255, 255));
        EmailTextRegistro.setText("E-mail");
        getContentPane().add(EmailTextRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        RegistroText.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        RegistroText.setForeground(new java.awt.Color(255, 255, 255));
        RegistroText.setText("REGISTRO");
        getContentPane().add(RegistroText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 700, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CaixaRegistrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaRegistrarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaRegistrarSenhaActionPerformed

    private void CaixaRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaRegistrarUsuarioActionPerformed

    private void CaixaRegistrarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaRegistrarEmailActionPerformed
       
    }//GEN-LAST:event_CaixaRegistrarEmailActionPerformed

    private void BotaoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRegistrarActionPerformed
        
        if(CaixaRegistrarSenha.getText().matches("")||CaixaRegistrarUsuario.getText().matches("")||CaixaRegistrarEmail.getText().matches("")){
            JOptionPane.showMessageDialog(rootPane, "Todos os campos precisam estar preenchidos");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Cadastro Realizado!!!");
            
            try {
            LoginController cadastro = new LoginController();
            cadastro.cadastroUsuario(this);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setVisible(false);
        }
        
        
        
        
    }//GEN-LAST:event_BotaoRegistrarActionPerformed

    public JTextField getCaixaRegistrarEmail() {
        return CaixaRegistrarEmail;
    }

    public void setCaixaRegistrarEmail(JTextField CaixaRegistrarEmail) {
        this.CaixaRegistrarEmail = CaixaRegistrarEmail;
    }

    public JTextField getCaixaRegistrarSenha() {
        return CaixaRegistrarSenha;
    }

    public void setCaixaRegistrarSenha(JTextField CaixaRegistrarSenha) {
        this.CaixaRegistrarSenha = CaixaRegistrarSenha;
    }

    public JTextField getCaixaRegistrarUsuario() {
        return CaixaRegistrarUsuario;
    }

    public void setCaixaRegistrarUsuario(JTextField CaixaRegistrarUsuario) {
        this.CaixaRegistrarUsuario = CaixaRegistrarUsuario;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoRegistrar;
    private javax.swing.JTextField CaixaRegistrarEmail;
    private javax.swing.JTextField CaixaRegistrarSenha;
    private javax.swing.JTextField CaixaRegistrarUsuario;
    private javax.swing.JLabel EmailTextRegistro;
    private javax.swing.JLabel RegistroText;
    private javax.swing.JLabel SenhaTextRegistro;
    private javax.swing.JLabel UsuarioTextRegistro;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
