/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Temis juninho
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoRegistrar = new javax.swing.JButton();
        RegistrarUsuario = new javax.swing.JTextField();
        CaixaRegistrarSenha = new javax.swing.JTextField();
        CaixaRegistrarEmail = new javax.swing.JTextField();
        UsuarioTextRegistro = new javax.swing.JLabel();
        SenhaTextRegistro = new javax.swing.JLabel();
        EmailTextRegistro = new javax.swing.JLabel();
        RegistroText = new javax.swing.JLabel();
        TheWitcherTelaRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoRegistrar.setText("Registrar");
        getContentPane().add(BotaoRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 90, 30));

        RegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(RegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 170, 30));

        CaixaRegistrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaRegistrarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaRegistrarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 170, 30));

        CaixaRegistrarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaRegistrarEmailActionPerformed(evt);
            }
        });
        getContentPane().add(CaixaRegistrarEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 170, 30));

        UsuarioTextRegistro.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        UsuarioTextRegistro.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioTextRegistro.setText("Usuario");
        getContentPane().add(UsuarioTextRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        SenhaTextRegistro.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        SenhaTextRegistro.setForeground(new java.awt.Color(255, 255, 255));
        SenhaTextRegistro.setText("Senha");
        getContentPane().add(SenhaTextRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        EmailTextRegistro.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        EmailTextRegistro.setForeground(new java.awt.Color(255, 255, 255));
        EmailTextRegistro.setText("E-mail");
        getContentPane().add(EmailTextRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        RegistroText.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        RegistroText.setForeground(new java.awt.Color(255, 255, 255));
        RegistroText.setText("REGISTRO");
        getContentPane().add(RegistroText, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        TheWitcherTelaRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dados/TheWitcherTelaRegistro.jpeg"))); // NOI18N
        getContentPane().add(TheWitcherTelaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CaixaRegistrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaRegistrarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaRegistrarSenhaActionPerformed

    private void RegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarUsuarioActionPerformed

    private void CaixaRegistrarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaRegistrarEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixaRegistrarEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoRegistrar;
    private javax.swing.JTextField CaixaRegistrarEmail;
    private javax.swing.JTextField CaixaRegistrarSenha;
    private javax.swing.JLabel EmailTextRegistro;
    private javax.swing.JTextField RegistrarUsuario;
    private javax.swing.JLabel RegistroText;
    private javax.swing.JLabel SenhaTextRegistro;
    private javax.swing.JLabel TheWitcherTelaRegistro;
    private javax.swing.JLabel UsuarioTextRegistro;
    // End of variables declaration//GEN-END:variables
}
