/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MenuController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author temis
 */
public class TelaCasaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCasaCadastro
     */
    public TelaCasaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caixacasacadastro1 = new javax.swing.JTextField();
        caixacasacadastro2 = new javax.swing.JTextField();
        caixacasacadastro3 = new javax.swing.JTextField();
        Caixacasaid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BotaoRegistrarcasa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        caixacasacadastro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixacasacadastro1ActionPerformed(evt);
            }
        });
        getContentPane().add(caixacasacadastro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 106, 141, 41));

        caixacasacadastro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixacasacadastro2ActionPerformed(evt);
            }
        });
        getContentPane().add(caixacasacadastro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 165, 141, 45));

        caixacasacadastro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixacasacadastro3ActionPerformed(evt);
            }
        });
        getContentPane().add(caixacasacadastro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 228, 141, 44));

        Caixacasaid.setText("ID");
        Caixacasaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixacasaidActionPerformed(evt);
            }
        });
        getContentPane().add(Caixacasaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 11, 85, 45));

        jLabel1.setText("endereço");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 112, -1, 29));

        jLabel2.setText("Numero de quartos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 165, -1, -1));

        jLabel3.setText("metros quadrados");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 228, -1, -1));

        BotaoRegistrarcasa.setText("Registrar casa");
        BotaoRegistrarcasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRegistrarcasaActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoRegistrarcasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 324, 159, 56));

        jPanel1.setBackground(new java.awt.Color(204, 0, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixacasacadastro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixacasacadastro3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixacasacadastro3ActionPerformed

    private void caixacasacadastro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixacasacadastro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixacasacadastro2ActionPerformed

    private void BotaoRegistrarcasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRegistrarcasaActionPerformed
      
      if (caixacasacadastro1.getText().matches("") || caixacasacadastro2.getText().matches("") || caixacasacadastro3.getText().matches("") || Caixacasaid.getText().matches("")) {
    JOptionPane.showMessageDialog(rootPane, "Todos os campos precisam estar preenchidos");
} else {
    try {
        MenuController cadastro = new MenuController();
        cadastro.cadastroCasas(this);
    } catch (SQLException ex) {
        Logger.getLogger(TelaCasaCadastro.class.getName()).log(Level.SEVERE, null, ex);
    }
    this.setVisible(false);
}

    }//GEN-LAST:event_BotaoRegistrarcasaActionPerformed

    private void caixacasacadastro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixacasacadastro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixacasacadastro1ActionPerformed

    private void CaixacasaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixacasaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaixacasaidActionPerformed

    public JTextField getCaixacasaid() {
        return Caixacasaid;
    }

    public void setCaixacasaid(JTextField Caixacasaid) {
        this.Caixacasaid = Caixacasaid;
    }

    public JTextField getCaixacasacadastro1() {
        return caixacasacadastro1;
    }

    public void setCaixacasacadastro1(JTextField caixacasacadastro1) {
        this.caixacasacadastro1 = caixacasacadastro1;
    }

    public JTextField getCaixacasacadastro2() {
        return caixacasacadastro2;
    }

    public void setCaixacasacadastro2(JTextField caixacasacadastro2) {
        this.caixacasacadastro2 = caixacasacadastro2;
    }

    public JTextField getCaixacasacadastro3() {
        return caixacasacadastro3;
    }

    public void setCaixacasacadastro3(JTextField caixacasacadastro3) {
        this.caixacasacadastro3 = caixacasacadastro3;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCasaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCasaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCasaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCasaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCasaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoRegistrarcasa;
    private javax.swing.JTextField Caixacasaid;
    private javax.swing.JTextField caixacasacadastro1;
    private javax.swing.JTextField caixacasacadastro2;
    private javax.swing.JTextField caixacasacadastro3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
